# Generated by Django 4.1.6 on 2023-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('theme', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagePost')),
                ('contenu', models.TextField(blank=True)),
                ('blogPoster', models.CharField(blank=True, max_length=128)),
                ('joinPiece', models.URLField(blank=True)),
            ],
        ),
    ]
