# Generated by Django 4.1.6 on 2023-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidepyApp', '0002_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.IntegerField(default=0)),
                ('anneeSortie', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=128)),
                ('nom', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='imageCv')),
                ('Cv', models.URLField(blank=True)),
            ],
        ),
    ]
