# Generated by Django 4.1.6 on 2023-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidepyApp', '0003_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='domaine',
            field=models.CharField(max_length=128),
        ),
    ]
