# Generated by Django 4.1.6 on 2023-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidepyApp', '0009_alter_partner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='domaine',
            field=models.CharField(choices=[('GC', 'Genie_civil'), ('GI', 'Genie_informatique'), ('GM', 'Genie_mécanique'), ('GE', 'Genie_électrique'), ('GIND', 'Genie_industriel'), ('GF', 'Genie_financier'), ('AN', 'Art_numérique'), ('HN', 'Humanité_numérique'), ('GMET', 'Genie_météo')], max_length=128),
        ),
    ]
