# Generated by Django 4.1.6 on 2023-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidepyApp', '0010_alter_cv_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
